# Dockerfile for server.py (Backend 2)

FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the backend code for server.py
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirments.txt

# Expose port for server.py
EXPOSE 5001

# Run server.py
CMD ["python", "server.py"]
