version: '3.8'

services:
  # Backend 1 for app.py
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    networks:
      - backend_network

  # Backend 2 for server.py
  backend2:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5001:5001"
    networks:
      - backend_network

  # Frontend (React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend_network

# Define networks
networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

